Repository LIKELION-Android-Bootcamp-4th/Todori, pull requests merged in 2025-08, with the labels that each got.

#2 [UI/T01] Todo 화면 ( 개인, 목표, 스터디 ) UI 구성
  app/build.gradle.kts
  app/src/main/java/com/mukmuk/todori/MainActivity.kt
  app/src/main/java/com/mukmuk/todori/data/remote/goal/Goal.kt
  app/src/main/java/com/mukmuk/todori/data/remote/goal/GoalTodo.kt
  app/src/main/java/com/mukmuk/todori/data/remote/study/Study.kt
  app/src/main/java/com/mukmuk/todori/data/remote/study/StudyMember.kt
  app/src/main/java/com/mukmuk/todori/data/remote/study/StudyTodo.kt
  app/src/main/java/com/mukmuk/todori/data/remote/study/TodoProgress.kt
  app/src/main/java/com/mukmuk/todori/data/remote/todo/Todo.kt
  app/src/main/java/com/mukmuk/todori/data/remote/todo/TodoCategory.kt
  app/src/main/java/com/mukmuk/todori/navigation/AppNavigation.kt
  app/src/main/java/com/mukmuk/todori/ui/component/ProgressBar.kt
  app/src/main/java/com/mukmuk/todori/ui/component/SimpleTopAppBAr.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/CreateCategoryScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/CreateGoalScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/CreateStudyScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/TodoScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/CardHeaderSection.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/GoalTodoList.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/ProgressWithText.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/StudyTodoList.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/TodoItemRow.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/TodoList.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/TodoTopBar.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/WeekCalendar.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/card/GoalCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/card/StudyCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/card/TodoCard.kt
  app/src/main/java/com/mukmuk/todori/ui/theme/AppDimens.kt
  app/src/main/java/com/mukmuk/todori/ui/theme/Color.kt
  gradle/libs.versions.toml
Labels: ui

#3 [UI/T02] 개인 카테고리 생성 페이지
  app/build.gradle.kts
  app/src/main/java/com/mukmuk/todori/MainActivity.kt
  app/src/main/java/com/mukmuk/todori/data/remote/goal/Goal.kt
  app/src/main/java/com/mukmuk/todori/data/remote/goal/GoalTodo.kt
  app/src/main/java/com/mukmuk/todori/data/remote/study/Study.kt
  app/src/main/java/com/mukmuk/todori/data/remote/study/StudyMember.kt
  app/src/main/java/com/mukmuk/todori/data/remote/study/StudyTodo.kt
  app/src/main/java/com/mukmuk/todori/data/remote/study/TodoProgress.kt
  app/src/main/java/com/mukmuk/todori/data/remote/todo/Todo.kt
  app/src/main/java/com/mukmuk/todori/data/remote/todo/TodoCategory.kt
  app/src/main/java/com/mukmuk/todori/navigation/AppNavigation.kt
  app/src/main/java/com/mukmuk/todori/ui/component/ProgressBar.kt
  app/src/main/java/com/mukmuk/todori/ui/component/SimpleTopAppBAr.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/CreateCategoryScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/CreateGoalScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/CreateStudyScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/TodoScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/CardHeaderSection.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/GoalTodoList.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/ProgressWithText.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/StudyTodoList.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/TodoItemRow.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/TodoList.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/TodoTopBar.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/WeekCalendar.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/card/GoalCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/card/StudyCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/card/TodoCard.kt
  app/src/main/java/com/mukmuk/todori/ui/theme/AppDimens.kt
  app/src/main/java/com/mukmuk/todori/ui/theme/Color.kt
  gradle/libs.versions.toml
Labels: ui

#6 [UI/T04] 스터디 생성 페이지
  app/src/main/java/com/mukmuk/todori/navigation/AppNavigation.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/CreateStudyScreen.kt
Labels: ui

#9 [UI/D02] 목표 로드맵 상세 화면 UI 제작 & 목표 수정 화면 전환 처리
  app/src/main/java/com/mukmuk/todori/data/remote/goal/Goal.kt
  app/src/main/java/com/mukmuk/todori/navigation/AppNavigation.kt
  app/src/main/java/com/mukmuk/todori/ui/component/TodoItemEditRow.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/CreateGoalScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/TodoScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/CardHeaderSection.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/GoalPeriodStatus.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/GoalProgressSection.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/GoalTodoList.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/SingleDatePickerBottomSheet.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/card/GoalCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/card/StudyCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/GoalDetailScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/TodoDetailScreen.kt
  app/src/main/java/com/mukmuk/todori/util/calculateDDayValue.kt
Labels: ui

#8 [UI/U01] 마이페이지 화면 제작
  app/src/main/java/com/mukmuk/todori/data/model/User.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/mypage/MyPageScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/mypage/component/AccountSection.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/mypage/component/MyPageMenuSection.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/mypage/component/ProfileSection.kt
  app/src/main/java/com/mukmuk/todori/util/LevelUtils.kt
  app/src/main/res/drawable/ic_fire1.png
  app/src/main/res/drawable/ic_flag1.png
  app/src/main/res/drawable/ic_level3.png
  app/src/main/res/drawable/ic_profile1.png
Labels: ui

#12 [UI/U02] 마이페이지 - 나의 레벨 화면 제작
  app/src/main/java/com/mukmuk/todori/data/dummy/QuestDummy.kt
  app/src/main/java/com/mukmuk/todori/data/remote/quest/DailyQuest.kt
  app/src/main/java/com/mukmuk/todori/data/remote/quest/Quest.kt
  app/src/main/java/com/mukmuk/todori/data/remote/user/User.kt
  app/src/main/java/com/mukmuk/todori/navigation/AppNavigation.kt
  app/src/main/java/com/mukmuk/todori/ui/component/SimpleTopAppBar.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/mypage/MyLevelScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/mypage/MyPageScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/mypage/component/PointProgressBar.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/mypage/component/ProfileSection.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/mypage/component/QuestSection.kt
  app/src/main/java/com/mukmuk/todori/ui/theme/AppTextStyle.kt
Labels: ui

#13 [UI/U03] 완료한 목표 화면 제작
  app/src/main/java/com/mukmuk/todori/navigation/AppNavigation.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/mypage/CompletedGoalsScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/mypage/MyPageScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/mypage/component/CompletedGoalCard.kt
Labels: ui

#14 [UI/M01] 리셋 버튼 버그 수정
  app/src/main/java/com/mukmuk/todori/ui/screen/home/HomeState.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/home/HomeViewModel.kt
Labels: bug

#15 [UI/U04] 프로필 관리 화면 제작
  app/src/main/java/com/mukmuk/todori/navigation/AppNavigation.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/mypage/MyPageScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/mypage/ProfileManagementScreen.kt
  app/src/main/java/com/mukmuk/todori/util/LevelUtils.kt
  app/src/main/res/drawable/ic_level1.png
  app/src/main/res/drawable/ic_level2.png
  app/src/main/res/drawable/ic_level4.png
  app/src/main/res/drawable/ic_level5.png
  app/src/main/res/drawable/ic_level6.png
Labels: ui

#16 [UI/L01] 로그인 및 회원가입 화면 제작
  app/src/main/java/com/mukmuk/todori/navigation/AppNavigation.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/login/LoginEvent.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/login/LoginScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/login/LoginState.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/login/LoginViewModel.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/mypage/MyPageScreen.kt
Labels: ui

#18 [fix/firebase_setting] firebase error 수정
  gradle/libs.versions.toml
Labels: fix

#26 [feature/TODO-007] 스터디 생성 통신 완료
  app/src/main/java/com/mukmuk/todori/data/repository/StudyRepository.kt
  app/src/main/java/com/mukmuk/todori/data/service/StudyService.kt
  app/src/main/java/com/mukmuk/todori/di/AppModule.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/create/CreateStudyScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/create/StudyViewModel.kt
Labels: feature

#28 [Feat/USER-001] 프로필 수정 기능
  app/src/main/java/com/mukmuk/todori/data/repository/UserRepository.kt
  app/src/main/java/com/mukmuk/todori/data/service/UserService.kt
  app/src/main/java/com/mukmuk/todori/di/AppModule.kt
  app/src/main/java/com/mukmuk/todori/navigation/AppNavigation.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/mypage/MyPageScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/mypage/ProfileManagementScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/mypage/ProfileViewModel.kt
Labels: feature

#11 [UI/s01] 통계 화면 제작
  app/build.gradle.kts
  app/src/main/java/com/mukmuk/todori/data/remote/dailyRecord/DailyRecord.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/StatsScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/CalendarCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/DayStatsCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/MonthCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/MonthProgress.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/WeekCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/WeekGraph.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/WeekProgress.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/tab/DayTab.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/tab/MonthTab.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/tab/WeekTab.kt
  app/src/main/java/com/mukmuk/todori/ui/theme/Color.kt
  app/src/main/res/drawable/icon_alltime.xml
  app/src/main/res/drawable/icon_average.xml
  app/src/main/res/drawable/icon_check.xml
  app/src/main/res/drawable/icon_completed_goal.xml
  settings.gradle.kts
Labels: ui

#31 [chore/font2] AppTextStyle 추가
  app/src/main/java/com/mukmuk/todori/ui/theme/AppTextStyle.kt
Labels: chore

#30 [UI/C04] 커뮤니티 상세 화면 제작
  app/src/main/java/com/mukmuk/todori/MainActivity.kt
  app/src/main/java/com/mukmuk/todori/navigation/AppNavigation.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/CommunityScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/CommunityViewModel.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/components/CommentList.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/components/CommunityDetailComment.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/components/CommunityDetailCommentReply.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/components/CommunityDetailItem.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/components/CommunityListItem.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/components/CommunityListItemData.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/components/CommunityListOption.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/components/CommunitySearchData.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/components/ListPickerBottomSheet.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/create/CreateCommunityScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/detail/CommunityDetailScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/search/CommunitySearchScreen.kt
  app/src/main/res/drawable/ic_comment.png
  gradle/libs.versions.toml
Labels: ui

#32 [Feature/TODO-001] TODO 관련 기능
  app/src/main/java/com/mukmuk/todori/data/remote/todo/Todo.kt
  app/src/main/java/com/mukmuk/todori/data/repository/TodoCategoryRepository.kt
  app/src/main/java/com/mukmuk/todori/data/repository/TodoRepository.kt
  app/src/main/java/com/mukmuk/todori/data/service/TodoCategoryService.kt
  app/src/main/java/com/mukmuk/todori/data/service/TodoService.kt
  app/src/main/java/com/mukmuk/todori/di/AppModule.kt
  app/src/main/java/com/mukmuk/todori/navigation/AppNavigation.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/home/HomeScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/TodoScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/create/CreateCategoryScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/create/TodoCategoryState.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/create/TodoCategoryViewModel.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/todo/TodoDetailScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/todo/TodoDetailState.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/todo/TodoDetailViewModel.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/list/TodoList.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/list/todo/TodoList.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/list/todo/TodoListState.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/list/todo/TodoListViewModel.kt
  app/src/main/java/com/mukmuk/todori/util/DateUtil.kt
Labels: feature

#35 [Feature/MYP-003] 완료한 목표 리스트 연동
  app/src/main/java/com/mukmuk/todori/data/remote/goal/Goal.kt
  app/src/main/java/com/mukmuk/todori/data/service/UserService.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/mypage/CompletedGoalsScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/mypage/CompletedGoalsViewModel.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/DayStatsCard.kt
Labels: feature

#39 [feature/STATS-009] 통계화면 WEEK탭 TODO 연동
  app/src/main/java/com/mukmuk/todori/data/repository/TodoRepository.kt
  app/src/main/java/com/mukmuk/todori/data/service/TodoService.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/StatsScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/WeekCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/WeekProgress.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/tab/day/DayTab.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/tab/month/MonthTab.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/tab/week/WeekTab.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/tab/week/WeekViewModel.kt
Labels: feature

#40 [Feature/STUDY] STUDY 기능 완성....
  app/src/main/java/com/mukmuk/todori/data/remote/study/Study.kt
  app/src/main/java/com/mukmuk/todori/data/remote/study/TodoProgress.kt
  app/src/main/java/com/mukmuk/todori/data/repository/StudyRepository.kt
  app/src/main/java/com/mukmuk/todori/data/service/StudyService.kt
  app/src/main/java/com/mukmuk/todori/navigation/AppNavigation.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/MemberProgressCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/StudyCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/StudyTodoInputCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/create/CreateStudyScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/create/StudyViewModel.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/MemberProgressDetailScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/StudyDetailScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/study/StudyDetailScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/study/StudyDetailState.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/study/StudyDetailViewModel.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/list/study/StudyListViewModel.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/list/study/StudyTodoList.kt
Labels: feature

#41 [Feature/STATS-007] 통계 - Month 탭 연동완료
  app/src/main/java/com/mukmuk/todori/data/repository/DailyRecordRepository.kt
  app/src/main/java/com/mukmuk/todori/data/repository/GoalStatsRepository.kt
  app/src/main/java/com/mukmuk/todori/data/repository/StudyStatsRepository.kt
  app/src/main/java/com/mukmuk/todori/data/repository/TodoStatsRepository.kt
  app/src/main/java/com/mukmuk/todori/data/service/DailyRecordService.kt
  app/src/main/java/com/mukmuk/todori/data/service/StudyService.kt
  app/src/main/java/com/mukmuk/todori/data/service/TodoStatsService.kt
  app/src/main/java/com/mukmuk/todori/di/AppModule.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/StatsScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/MonthCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/MonthProgress.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/tab/month/MonthState.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/tab/month/MonthTab.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/tab/month/MonthViewModel.kt
Labels: feature

#45 [Feature/TMR-001] 타이머 데이터 연동
  app/build.gradle.kts
  app/src/main/java/com/mukmuk/todori/data/local/datastore/HomeSettingPreferencesKeys.kt
  app/src/main/java/com/mukmuk/todori/data/local/datastore/HomeSettingRepository.kt
  app/src/main/java/com/mukmuk/todori/data/local/datastore/RecordRepository.kt
  app/src/main/java/com/mukmuk/todori/data/repository/HomeRepository.kt
  app/src/main/java/com/mukmuk/todori/data/repository/TodoRepository.kt
  app/src/main/java/com/mukmuk/todori/data/service/HomeService.kt
  app/src/main/java/com/mukmuk/todori/data/service/TodoService.kt
  app/src/main/java/com/mukmuk/todori/di/AppModule.kt
  app/src/main/java/com/mukmuk/todori/navigation/AppNavigation.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/home/HomeScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/home/HomeState.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/home/HomeViewModel.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/home/components/TimerTextFieldInput.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/home/home_setting/HomeSettingScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/home/home_setting/HomeSettingViewModel.kt
  gradle/libs.versions.toml
Labels: feature

#47 [Feature/STATS-005] Week tab 연동
  app/src/main/java/com/mukmuk/todori/data/repository/DailyRecordRepository.kt
  app/src/main/java/com/mukmuk/todori/data/service/DailyRecordService.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/MonthCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/WeekCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/WeekGraph.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/tab/week/WeekState.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/tab/week/WeekTab.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/tab/week/WeekViewModel.kt
Labels: feature

#50 [UI/L01] 로그인 버튼 번경
  app/src/main/java/com/mukmuk/todori/ui/screen/login/LoginScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/login/components/LoginButton.kt
  app/src/main/java/com/mukmuk/todori/ui/theme/Color.kt
  app/src/main/res/drawable/ic_google_logo.xml
  app/src/main/res/drawable/ic_kakao_logo.png
  app/src/main/res/drawable/ic_naver_logo.png
Labels: ui

#53 [Fix/MYP] 프로필 연결 uid로 변경
  app/src/main/java/com/mukmuk/todori/ui/screen/mypage/CompletedGoalsViewModel.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/mypage/ProfileManagementScreen.kt
Labels: feature, fix

#52 [Feature/TODO] 투두 uid -> 로그인한 사용자로 변경
  app/src/main/java/com/mukmuk/todori/data/repository/StudyRepository.kt
  app/src/main/java/com/mukmuk/todori/data/repository/UserRepository.kt
  app/src/main/java/com/mukmuk/todori/data/service/StudyService.kt
  app/src/main/java/com/mukmuk/todori/data/service/UserService.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/TodoScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/TodoViewModel.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/MemberProgressCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/MemberProgressRow.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/WeekCalendar.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/create/CreateCategoryScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/create/GoalViewModel.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/create/StudyViewModel.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/MemberProgressDetailScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/goal/GoalDetailScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/study/StudyDetailScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/study/StudyDetailState.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/study/StudyDetailViewModel.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/todo/TodoDetailScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/list/goal/GoalTodoList.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/list/study/StudyTodoList.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/list/todo/TodoList.kt
  app/src/main/java/com/mukmuk/todori/ui/theme/Color.kt
  app/src/main/java/com/mukmuk/todori/util/LevelUtils.kt
  app/src/main/res/drawable/leader.png
Labels: feature, fix

#51 [Feat/TMR-001] 현재 로그인 한 계정 uid 연결
  app/src/main/java/com/mukmuk/todori/ui/screen/home/HomeScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/home/HomeState.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/home/HomeViewModel.kt
Labels: feature

#56 [Fix/TMR-001] 수정
  app/src/main/java/com/mukmuk/todori/navigation/AppNavigation.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/home/HomeScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/home/HomeViewModel.kt
Labels: fix

#54 [fix/completedGoal] 끝난 목표 testuser -> uid 변경
  app/src/main/java/com/mukmuk/todori/ui/screen/mypage/CompletedGoalsScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/mypage/CompletedGoalsViewModel.kt
Labels: fix

#42 [Feature/stats-002] 통계화면 DAY탭 TODO 연동
  app/src/main/java/com/mukmuk/todori/data/repository/DailyRecordRepository.kt
  app/src/main/java/com/mukmuk/todori/data/repository/TodoRepository.kt
  app/src/main/java/com/mukmuk/todori/data/service/DailyRecordService.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/StatsScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/CalendarCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/DayStatsCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/WeekProgress.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/tab/day/DayTab.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/tab/day/DayViewModel.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/tab/month/MonthTab.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/tab/week/WeekTab.kt
Labels: feature

#57 [Feature/TMR-005] 타이머 직접 시간 입력
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mukmuk/todori/data/repository/HomeRepository.kt
  app/src/main/java/com/mukmuk/todori/data/service/HomeService.kt
  app/src/main/java/com/mukmuk/todori/di/AppModule.kt
  app/src/main/java/com/mukmuk/todori/navigation/AppNavigation.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/home/HomeScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/home/HomeViewModel.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/home/components/TimerTextFieldInput2.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/home/home_ocr/HomeOcrScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/home/home_ocr/HomeOcrState.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/home/home_ocr/HomeOcrViewModel.kt
  gradle/libs.versions.toml
Labels: ui, feature

#69 [Fix/TMR-005] OCR 삭제
  app/src/main/java/com/mukmuk/todori/ui/screen/home/home_ocr/HomeOcrScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/home/home_ocr/HomeOcrState.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/home/home_ocr/HomeOcrViewModel.kt
Labels: fix

#70 [Feature/widget-002] 위젯 추가(목표 디데이)
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/create/CreateGoalScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/create/GoalViewModel.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/goal/GoalDetailViewModel.kt
  app/src/main/java/com/mukmuk/todori/ui/theme/WidgetTextStyle.kt
  app/src/main/java/com/mukmuk/todori/widget/WidgetUpdateDispatcher.kt
  app/src/main/java/com/mukmuk/todori/widget/goaldaycount/DayCountWidget.kt
  app/src/main/java/com/mukmuk/todori/widget/goaldaycount/DayCountWidgetReceiver.kt
  app/src/main/java/com/mukmuk/todori/widget/goaldaycount/DayCountWorker.kt
  app/src/main/java/com/mukmuk/todori/widget/goaldaycount/DayCountWorkerEntryPoint.kt
  app/src/main/res/xml/widget_day_count.xml
Labels: feature

#71 [Feature/FCM-001] 알림 보내기 FCM 완성
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mukmuk/todori/MainActivity.kt
  app/src/main/java/com/mukmuk/todori/TodoriApplication.kt
  app/src/main/java/com/mukmuk/todori/data/service/MyFirebaseMessagingService.kt
  app/src/main/java/com/mukmuk/todori/navigation/AppNavigation.kt
  app/src/main/java/com/mukmuk/todori/util/NotificationHelper.kt
  app/src/main/java/com/mukmuk/todori/util/NotificationPermission.kt
Labels: feature

#72 [Fix/WGT-0012] 위젯 배경 추가
  app/src/main/java/com/mukmuk/todori/widget/timer/TimerWidget.kt
  app/src/main/java/com/mukmuk/todori/widget/totaltime/TotalTimeWidget.kt
Labels: fix

#73 [Fix/TMR-005] 타이머 추가 시 홈 화면 바로 업데이트
  app/src/main/java/com/mukmuk/todori/ui/screen/home/HomeViewModel.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/home/home_ocr/HomeOcrViewModel.kt
  app/src/main/java/com/mukmuk/todori/widget/timer/TimerService.kt
Labels: fix

#74 [Feat/WEEK-STAT] 주간 통계 UI & 로직 처리
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/StatsScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/WeekCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/WeekGraph.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/WeekProgress.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/day/CalendarCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/week/HeatmapGrid.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/week/SetupCombinedChart.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/week/StatItem.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/week/StudyStatisticsSection.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/week/TimePerformanceHeatmap.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/week/WeekInsights.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/tab/day/DayTab.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/tab/week/WeekState.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/tab/week/WeekTab.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/tab/week/WeekViewModel.kt
  app/src/main/java/com/mukmuk/todori/ui/theme/AppTextStyle.kt
  app/src/main/java/com/mukmuk/todori/ui/theme/Color.kt
  app/src/main/java/com/mukmuk/todori/ui/theme/Dimens.kt
  app/src/main/java/com/mukmuk/todori/util/DateUtil.kt
  app/src/main/java/com/mukmuk/todori/util/StatUtils.kt
  app/src/main/res/drawable/fill_actual.xml
  app/src/main/res/drawable/fill_planned.xml
Labels: ui, refactor

#76 [Fix/widget 001] 카테고리 삭제 시 위젯 업데이트
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/todo/TodoDetailViewModel.kt
Labels: fix

#77 [fix/T01] TODO 화면 스크롤 추가
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/goal/GoalDetailScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/todo/TodoDetailScreen.kt
Labels: fix

#78 [fix/T01_2] 달력 공부시간 기준 통일
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/WeekCalendar.kt
Labels: fix

#86 [Feat/LOGIN-003] 로그아웃 시 다이얼로그
  app/src/main/java/com/mukmuk/todori/ui/screen/mypage/MyPageScreen.kt
Labels: feature

#88 [app_ic] 앱 아이콘 변경
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
Labels: ui

#90 [Fix/STUDY-001] 스터디 이슈관리
  app/src/main/java/com/mukmuk/todori/ui/screen/community/components/CommunityListData.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/components/StudyDetailCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/detail/CommunityDetailScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/StudyCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/StudyMetaInfoRow.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/StudyTodoInputCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/study/StudyDetailScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/list/study/StudyTodoList.kt
  app/src/main/java/com/mukmuk/todori/util/DateUtil.kt
Labels: fix

#93 [Feat/REPORT] 월간 리포트 완성
  app/src/main/java/com/mukmuk/todori/navigation/AppNavigation.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/MonthlyReportScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/StatsScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/report/CategoryProgress.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/report/CategoryProgressItem.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/report/CompletionRateCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/report/EncouragementCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/report/EnduranceCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/report/GoalProgressCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/report/HourlyHighlightCircle.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/report/LegendaryDayCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/report/MonthHeroCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/report/MonthlyReportHeader.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/report/StudyGoalCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/report/StudyStreakCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/tab/report/MonthlyReportState.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/tab/report/MonthlyReportViewModel.kt
  app/src/main/java/com/mukmuk/todori/ui/theme/Color.kt
Labels: ui, refactor

#95 [fix/splash] 사진 크기 조절 + 텍스트
  app/src/main/java/com/mukmuk/todori/ui/screen/splash/SplashScreen.kt
Labels: refactor

#96 [FIX/btm-nav] 백스택 오류 수정
  app/src/main/java/com/mukmuk/todori/MainActivity.kt
  app/src/main/java/com/mukmuk/todori/navigation/NavController.kt
Labels: fix

#98 [Fix/TODO-008] 목표 생성 / 수정 기간 이슈관리
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/DateRangePickerBottomSheet.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/create/CreateGoalScreen.kt
Labels: fix

#99 [Chore/Font] 폰트 Pretendard 로 변경
  app/src/main/java/com/mukmuk/todori/ui/screen/community/search/CommunitySearchScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/theme/AppFont.kt
  app/src/main/java/com/mukmuk/todori/ui/theme/AppTextStyle.kt
  app/src/main/res/font/notosans_bold.ttf
  app/src/main/res/font/notosans_light.ttf
  app/src/main/res/font/notosans_medium.ttf
  app/src/main/res/font/notosans_regular.ttf
  app/src/main/res/font/notosans_thin.ttf
  app/src/main/res/font/pretendard_bold.ttf
  app/src/main/res/font/pretendard_light.ttf
  app/src/main/res/font/pretendard_medium.ttf
  app/src/main/res/font/pretendard_regular.ttf
  app/src/main/res/font/pretendard_thin.ttf
Labels: chore

#101 [Feat/LOGIN-003] 최근 로그인 표시
  app/src/main/java/com/mukmuk/todori/data/local/datastore/AuthLocalRepository.kt
  app/src/main/java/com/mukmuk/todori/data/local/datastore/DataStoreModule.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/login/LoginScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/login/LoginViewModel.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/login/components/RecentLoginBox.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/mypage/ProfileViewModel.kt
Labels: feature

#102 [Fix/TMR-001] 홈 화면 Todo 이슈 관리
  app/src/main/java/com/mukmuk/todori/data/local/datastore/HomeSettingRepository.kt
  app/src/main/java/com/mukmuk/todori/data/local/datastore/RecordSettingRepository.kt
  app/src/main/java/com/mukmuk/todori/data/local/datastore/TodayTodoRepository.kt
  app/src/main/java/com/mukmuk/todori/data/repository/HomeRepository.kt
  app/src/main/java/com/mukmuk/todori/data/repository/TodoRepository.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/components/CommunityDetailComment.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/components/CommunityDetailCommentReply.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/components/CommunityListOption.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/components/CommunitySearchData.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/home/HomeScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/home/HomeViewModel.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/mypage/ProfileViewModel.kt
Labels: fix

#100 [refactor/Login] 로그인 화면 이미지 추가
  app/src/main/java/com/mukmuk/todori/ui/screen/login/LoginScreen.kt
  app/src/main/res/drawable/ic_level3_removebg.png
Labels: refactor

#97 [fix/todo_name] 개인 -> TODO 로 변경
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/TodoScreen.kt
Labels: refactor, fix

#67 [Feature/TODO-013] Url을 통한 카테고리 보내기 및 받기 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mukmuk/todori/data/remote/todo/SendCategory.kt
  app/src/main/java/com/mukmuk/todori/data/repository/TodoCategoryRepository.kt
  app/src/main/java/com/mukmuk/todori/data/repository/TodoRepository.kt
  app/src/main/java/com/mukmuk/todori/data/service/TodoCategoryService.kt
  app/src/main/java/com/mukmuk/todori/data/service/TodoService.kt
  app/src/main/java/com/mukmuk/todori/navigation/AppNavigation.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/CommunityScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/create/CreateCommunityScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/TodoScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/TodoState.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/TodoViewModel.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/CommonDetailAppBar.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/TodoCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/TodoCategoryListData.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/TodoCategoryPickerBottomSheet.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/todo/SendTodoDetailScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/todo/TodoDetailState.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/todo/TodoDetailViewModel.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/list/todo/TodoList.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/list/todo/TodoListState.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/list/todo/TodoListViewModel.kt
Labels: ui, feature

#89 [Fix/C01, C02, C03, C04] 맴버 수 바로 반영되게 수정
  app/src/main/java/com/mukmuk/todori/MainActivity.kt
  app/src/main/java/com/mukmuk/todori/data/repository/CommunityRepository.kt
  app/src/main/java/com/mukmuk/todori/data/service/CommunityService.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/CommunityScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/CommunityViewModel.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/components/StudyDetailCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/create/CreateCommunityScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/detail/CommunityDetailScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/detail/CommunityDetailViewModel.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/search/CommunitySearchScreen.kt
Labels: fix

#104 [Fix/t01_4] Todo 스터디 탭
  app/src/main/java/com/mukmuk/todori/data/repository/StudyRepository.kt
  app/src/main/java/com/mukmuk/todori/data/repository/UserRepository.kt
  app/src/main/java/com/mukmuk/todori/data/service/StudyService.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/mypage/ProfileViewModel.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/MemberProgressCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/StudyTodoInputCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/create/StudyViewModel.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/MemberProgressDetailScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/study/StudyDetailScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/study/StudyDetailViewModel.kt
Labels: fix

#111 [fix/completeGoal] 완료 목표 텍스트 옆 size 삭제 및 통신 시isLoading Indicator 추가
  app/src/main/java/com/mukmuk/todori/ui/screen/mypage/CompletedGoalsScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/mypage/CompletedGoalsViewModel.kt
Labels: refactor, fix

#112 [Fix/profile] 프로필 사진 & indicator
  app/src/main/java/com/mukmuk/todori/ui/screen/mypage/MyPageScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/mypage/component/ProfileSection.kt
Labels: refactor, fix

#118 [Fix/COM-002] 커뮤니티 생성 이슈 관리
  app/src/main/java/com/mukmuk/todori/data/remote/study/MyStudy.kt
  app/src/main/java/com/mukmuk/todori/data/repository/StudyRepository.kt
  app/src/main/java/com/mukmuk/todori/data/service/StudyService.kt
  app/src/main/java/com/mukmuk/todori/navigation/AppNavigation.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/CommunityScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/CommunityViewModel.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/StudyCategory.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/components/CommunityListData.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/components/ListPickerBottomSheet.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/components/TagPickerBottomSheet.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/create/CreateCommunityEvent.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/create/CreateCommunityScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/create/CreateCommunityState.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/create/CreateCommunityViewModel.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/detail/CommunityDetailViewModel.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/StudyMetaInfoRow.kt
Labels: feature, fix

#119 [FIX/FCM-001] 로그아웃시 알림 토큰 삭제
  app/src/main/java/com/mukmuk/todori/data/service/AuthService.kt
  app/src/main/java/com/mukmuk/todori/data/service/MyFirebaseMessagingService.kt
Labels: fix

#120 [feature] quest/ fcm js 파일 업로드
  functions/index.js
  functions/notify.js
  functions/quests.js
Labels: feature

#121 [refactor/study] study Leader vs Member 일 경우에 따라 다르게 동작하도록 수정
  app/src/main/java/com/mukmuk/todori/data/repository/StudyRepository.kt
  app/src/main/java/com/mukmuk/todori/data/service/StudyService.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/StudyTodoInputCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/study/StudyDetailScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/study/StudyDetailViewModel.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/list/study/StudyTodoList.kt
Labels: refactor, fix

#123 [Feat/timer] TimerSetting TextInput -> Slider & dailyRecord 업데이트 로직
  app/src/main/java/com/mukmuk/todori/ui/screen/home/HomeViewModel.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/home/home_setting/HomeSettingScreen.kt
Labels: feature, refactor, fix

#125 [Fix/COM-00] 커뮤니티 이슈 관리
  app/src/main/java/com/mukmuk/todori/data/remote/community/StudyPost.kt
  app/src/main/java/com/mukmuk/todori/data/remote/community/StudyPostComment.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/CommentUiModel.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/CommunityScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/PostUiModel.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/components/CommunityDetailComment.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/detail/CommunityDetailScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/detail/CommunityDetailState.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/detail/CommunityDetailViewModel.kt
Labels: fix

#126 [FIX/quest] quest 회고 조건 변경
  functions/quests.js
Labels: fix

#127 [Fix/COM] 커뮤니티 이슈 관리
  app/src/main/java/com/mukmuk/todori/data/repository/StudyRepository.kt
  app/src/main/java/com/mukmuk/todori/data/service/CommunityService.kt
  app/src/main/java/com/mukmuk/todori/data/service/StudyService.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/components/StudyDetailCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/detail/CommunityDetailScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/detail/CommunityDetailViewModel.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/study/StudyDetailScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/study/StudyDetailViewModel.kt
Labels: fix

#130 [refactor/splash] splash 2초 딜레이 설정
  app/src/main/java/com/mukmuk/todori/ui/screen/splash/SplashScreen.kt
Labels: ui, refactor

#131 [Fix/COM-001] 태그 글자 잘림 수정
  app/src/main/java/com/mukmuk/todori/ui/screen/community/CommunityScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/components/CommunityPost.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/detail/CommunityDetailScreen.kt
Labels: fix

#128 [fix/keyboard] 키보드 오류 해결
  app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/study/StudyDetailScreen.kt
Labels: fix

#135 [FIX/c02] 최근 검색어 박스 수정
  app/src/main/java/com/mukmuk/todori/ui/screen/community/components/CommunitySearchData.kt
Labels: ui, fix

#137 Fix/stat
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/MonthlyReportScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/StatsScreen.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/MonthCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/day/CalendarCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/day/DayPaceCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/month/MonthHighlightCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/month/SubjectAnalysisCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/report/CompletionRateCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/report/EnduranceCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/report/GoalProgressCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/report/LegendaryDayCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/report/MonthHeroCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/report/StudyGoalCard.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/week/WeekInsights.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/tab/day/DayTab.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/tab/month/MonthTab.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/tab/month/MonthViewModel.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/stats/tab/report/MonthlyReportViewModel.kt
  app/src/main/java/com/mukmuk/todori/ui/theme/Color.kt
Labels: refactor, fix

#138 [fix/community] 커뮤니티 멤버 추가 오류 해결
  app/src/main/java/com/mukmuk/todori/data/repository/CommunityRepository.kt
  app/src/main/java/com/mukmuk/todori/data/service/CommunityService.kt
  app/src/main/java/com/mukmuk/todori/ui/screen/community/detail/CommunityDetailViewModel.kt
Labels: fix
